#!/usr/bin/env python3
"""Tag every translatable string in a page and emit a dictionary skeleton.

Walks <main>, finds elements whose content is plain text (no element children),
gives each a stable data-i18n key, and writes js/i18n-<page>.js holding the
English it found plus an empty Arabic side to fill in.

Keys are prefixed per page so the dictionaries can never collide with the
chrome dictionary in js/i18n.js, which is merged alongside them.

Elements that mix text with inline markup — a sentence wrapping a link, say —
are skipped and listed at the end, because the translator swaps textContent and
would drop the markup. Those need restructuring by hand.

    python3 scripts/extract-i18n.py            # all pages
    python3 scripts/extract-i18n.py about      # one page
"""

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PREFIX = {
    "index": "ix", "about": "ab", "contact": "co", "case-studies": "cs",
    "assessments": "as", "coaching": "cg", "speakers": "sp",
    "elearning": "el", "privacy": "pv", "terms": "tm",
}

# Elements whose text is worth translating.
TAGS = (
    "p|li|h1|h2|h3|h4|h5|h6|dt|dd|td|th|figcaption|blockquote|button|summary|"
    "span|div|option|label|a"
)

# Classes that are structural rather than prose, or numerals that read the same
# in both languages.
SKIP_CLASSES = {
    "service-num", "usecase-num", "num", "case-result-value", "stat-value",
    "field-error", "hp-field",
}

ELEMENT_RE = re.compile(
    r"<(%s)(\s[^>]*)?>([^<>]*)</\1>" % TAGS, re.S
)


def is_translatable(text):
    t = html.unescape(text).strip()
    if len(t) < 3:
        return False
    if not re.search(r"[A-Za-z]{3,}", t):          # numerals, arrows, symbols
        return False
    if re.match(r"^(https?:|mailto:|tel:)", t):
        return False
    if "@" in t and " " not in t:                   # bare email address
        return False
    if re.match(r"^\+?[\d\s\-()]+$", t):            # phone number
        return False
    return True


def attrs_of(raw):
    if not raw:
        return {}
    return dict(re.findall(r'([\w:-]+)="([^"]*)"', raw))


def process(page):
    path = ROOT / (page + ".html")
    text = path.read_text(encoding="utf-8")

    start = text.index("<main")
    end = text.index("</main>")
    head, body, tail = text[:start], text[start:end], text[end:]

    prefix = PREFIX[page]
    entries = []
    counter = [0]

    def sub(m):
        tag, raw, inner = m.group(1), m.group(2) or "", m.group(3)
        at = attrs_of(raw)
        if "data-i18n" in at:
            return m.group(0)
        if SKIP_CLASSES & set(at.get("class", "").split()):
            return m.group(0)
        if not is_translatable(inner):
            return m.group(0)
        counter[0] += 1
        key = "%s%d" % (prefix, counter[0])
        entries.append((key, html.unescape(inner).strip()))
        return "<%s%s data-i18n=\"%s\">%s</%s>" % (tag, raw, key, inner, tag)

    body = ELEMENT_RE.sub(sub, body)
    path.write_text(head + body + tail, encoding="utf-8")

    # Anything left with mixed inline markup, for the report.
    mixed = [
        html.unescape(re.sub(r"<[^>]+>", "", m)).strip()
        for m in re.findall(r"<p(?:\s[^>]*)?>(.*?)</p>", body, re.S)
        if "<" in m and "data-i18n" not in m
    ]

    out = ROOT / "js" / ("i18n-%s.js" % page)
    lines = [
        "/* EMFT — %s page, English/Arabic strings." % page,
        "   Generated by scripts/extract-i18n.py, then the Arabic written by hand.",
        "   Registered with the site-wide translator in js/i18n.js. */",
        "(function () {",
        "  'use strict';",
        "  if (!window.EMFT_I18N) return;",
        "  window.EMFT_I18N.register({",
        "    en: {",
    ]
    for key, value in entries:
        lines.append("      %s: %s," % (key, js_string(value)))
    lines += ["    },", "    ar: {"]
    for key, _ in entries:
        lines.append("      %s: ''," % key)
    lines += ["    }", "  });", "})();", ""]
    out.write_text("\n".join(lines), encoding="utf-8")

    print("%-14s %3d strings -> js/i18n-%s.js%s" % (
        page, len(entries), page,
        ("   (%d mixed-markup skipped)" % len(mixed)) if mixed else ""))
    return mixed


def js_string(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ") + "'"


pages = sys.argv[1:] or list(PREFIX)
skipped = {}
for page in pages:
    m = process(page)
    if m:
        skipped[page] = m

if skipped:
    print("\nMixed inline markup — translate by restructuring, not by key:")
    for page, items in skipped.items():
        for item in items:
            print("  [%s] %s" % (page, item[:100]))
